// unit_test/from_standard/logic_if/react/result/entry.react.js
function entry (_cONTEXT, _mETHODS, Rc/*= React.createElement*/) {
  return Rc("div", null, [
    Rc('div', {}, [
      (/*_if_0 = */_cONTEXT.attr1) && Rc('span', {}, "single if"),
      (_if_1 = _cONTEXT.attr2) && Rc('span', {}, "if with else if"),
      !_if_1 && (/*_if_2 = */(_cONTEXT.attr3)) && Rc('span', {}, "with else if bu no else"),
      (_if_3 = _cONTEXT.attr4) && Rc('span', {}, "if with else"),
      !_if_3 && Rc('span', {}, "else end"),
      (_if_4 = _cONTEXT.attr5) && Rc('span', {}, "if with .. "),
      !_if_4 && (_if_5 = (_cONTEXT.attr6)) && Rc('span', {}, "else if 6"),
      !_if_4 && !_if_5 && (_if_6 = (_cONTEXT.attr7)) && Rc('span', {}, "else if 7"),
      !_if_4 && !_if_5 && !_if_6 && (_if_7 = (_cONTEXT.attr8)) && Rc('span', {}, "else if 8"),
      !_if_4 && !_if_5 && !_if_6 && !_if_7 && Rc('span', {}, "else end")
    ]),
  ]);

  /*IF_VAR_DEFINE*/

  // var _if_0; // unused var
  var _if_1;
  // var _if_2; // unused var
  var _if_3;
  var _if_4;
  var _if_5;
  var _if_6;
  var _if_7;
}

// unit_test/to_standard/logic_if_else/vue/entry.vue
<script setup>
import { ref } from 'vue'

const attr1 = ref(1);
const attr2 = ref("2");
const attr3 = ref(3);
const attr4 = ref("4");
const attr5 = ref(1);
const attr6 = ref("6");
const attr7 = ref(7);
const attr8 = ref(8);
</script>

<template>
<div>
    <span v-if="attr1">single if</span>


    <span v-if="attr2">if with else if</span>
    <span v-else-if="attr3">with else if bu no else</span>

    <span v-if="attr4">if with else</span>
    <span v-else>else end</span>

    <span v-if="attr5">if with .. </span>
    <span v-else-if="attr6">else if 6</span>
    <span v-else-if="attr7">else if 7</span>
    <span v-else-if="attr8">else if 8</span>
    <span v-else>else end</span>

</div>
</template>

<style>
  div {
      background-color: blue;
  }
  div > span {
    background-color: red;
    height: 100px;
    width: 100px;
  }
</style>
