// unit_test/to_standard/comm_node/vue/entry.vue
<script setup>
import { ref } from 'vue'

const dynText = ref('Hello World!');
const attr1 = ref(1);
const attr2 = ref("2");

</script>

<template>
<div>
    <span>normarl text</span>
    <!-- single line comment-->
    <span>{{dynText}}</span>
    no tag text
    <!-- multi
        <fakeNode>
        <open-node
         line comment-->
    <img src="abc"/>
    <span :test='aa.bb[6]["77"].c'/>
    <div attr0="</div>" :attr123="attr1+attr2 + 'attr3'" data-attr="<div>"/>
</div>
</template>

<style>
  div {
      background-color: blue;
  }
  div > div {
    background-color: red;
    height: 100px;
    width: 100px;
    display: flex;
    flex-direction: row;
  }
</style>

// unit_test/from_standard/comm_node_wxmp/react/result/entry.react.js
function entry (_cONTEXT, _mETHODS, Rc/*= React.createElement*/) {
  return Rc("div", null, [
    Rc('div', {}, [
      Rc('span', {"className": "wxmp-text"}, "normarl text"),
      /*<!-- single line comment-->*/
      Rc('span', {"className": "wxmp-text"}, _cONTEXT.dynText),
      "\n    no tag text\n    ",
      /*<!-- multi
        <fakeNode>
        <open-node
         line comment-->*/
      Rc('img', {"src": "abc"} ),
      Rc('div', {"attr0": "</view>", "attr123": ((_cONTEXT.attr1 + _cONTEXT.attr2) + "attr3"), "data-__data-set-need-parse": 1,"data-attr": "\"<view>\""} )
    ]),
    Rc('span', {"className": "wxmp-text"}, "multi node"),
  ]);
}
